# Hallmark Python Demo: init, info, add, commit, checkout, status, and clone

## Setup

In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path

from hallmark import Repo
from hallmark.downloader import download_remote_data
from hallmark.error import DestinationExistsError

In [2]:
%%bash
rm -rf repo1
rm -rf hallmark-demo-clone
mkdir repo1

## 1. Initialize the hallmark repo

In [3]:
repo1 = Repo.init("repo1")

## 2. Create data files on `main`

In [4]:
%%bash
pushd repo1
for f in a{0,0.75}_i{0,30,60,90,120}.h5; do echo "$f" > "$f"; done
echo "Files in repo1/:"
ls *.h5
popd

~/Library/CloudStorage/OneDrive-Personal/imp_files/rohin_school/university_of_arizona/eht_software/hallmark/demo/repo1 ~/Library/CloudStorage/OneDrive-Personal/imp_files/rohin_school/university_of_arizona/eht_software/hallmark/demo
Files in repo1/:
a0.75_i0.h5
a0.75_i120.h5
a0.75_i30.h5
a0.75_i60.h5
a0.75_i90.h5
a0_i0.h5
a0_i120.h5
a0_i30.h5
a0_i60.h5
a0_i90.h5
~/Library/CloudStorage/OneDrive-Personal/imp_files/rohin_school/university_of_arizona/eht_software/hallmark/demo

## 3. Add files and commit on `main`

In [5]:
paraframe = repo1.add("a{a}_i{i}.h5")
paraframe

            path     a      i
0    a0.75_i0.h5  0.75    0.0
1  a0.75_i120.h5  0.75  120.0
2   a0.75_i30.h5  0.75   30.0
3   a0.75_i60.h5  0.75   60.0
4   a0.75_i90.h5  0.75   90.0
5       a0_i0.h5  0.00    0.0
6     a0_i120.h5  0.00  120.0
7      a0_i30.h5  0.00   30.0
8      a0_i60.h5  0.00   60.0
9      a0_i90.h5  0.00   90.0

This paraframe object will also be reflected in the data.tsv file.

In [6]:
repo1.status()

{'branch': 'main',
 'staged': {'added': ['a0.75_i0.h5',
   'a0.75_i120.h5',
   'a0.75_i30.h5',
   'a0.75_i60.h5',
   'a0.75_i90.h5',
   'a0_i0.h5',
   'a0_i120.h5',
   'a0_i30.h5',
   'a0_i60.h5',
   'a0_i90.h5'],
  'modified': [],
  'deleted': []},
 'worktree': {'modified': [], 'deleted': []},
 'untracked': []}

In [7]:
repo1.commit("add main dataset")

True

In [8]:
repo1.status()

{'branch': 'main',
 'staged': {'added': [], 'modified': [], 'deleted': []},
 'worktree': {'modified': [], 'deleted': []},
 'untracked': []}

In [9]:
%%bash
echo "Objects stored after commit:"
find repo1/.hm/objects -type f | wc -l

Objects stored after commit:
      10

### Commit log

In [10]:
print(repo1.log())

commit 12f54680e809cfc1bdde1dae667ad44d88822853
Author: rohinsant <rohinsant@dhcp-10-134-233-143.uawifi.arizona.edu>
Date:   Fri Apr 24 14:19:20 2026 -0700

    add main dataset

commit d2ebaa5f548c415b04892bb2508ae77e78854b74
Author: rohinsant <rohinsant@dhcp-10-134-233-143.uawifi.arizona.edu>
Date:   Fri Apr 24 14:17:25 2026 -0700

    Initial commit: local `.hm` repository

## 4. Demo for `repo.checkout('BRANCH')`

We use a temporary branch so the main workflow stays intact.

In [11]:
repo1.checkout("experiment")

True

In [12]:
%%bash
pushd repo1
ls *.h5
popd

~/Library/CloudStorage/OneDrive-Personal/imp_files/rohin_school/university_of_arizona/eht_software/hallmark/demo/repo1 ~/Library/CloudStorage/OneDrive-Personal/imp_files/rohin_school/university_of_arizona/eht_software/hallmark/demo
a0.75_i0.h5
a0.75_i120.h5
a0.75_i30.h5
a0.75_i60.h5
a0.75_i90.h5
a0_i0.h5
a0_i120.h5
a0_i30.h5
a0_i60.h5
a0_i90.h5
~/Library/CloudStorage/OneDrive-Personal/imp_files/rohin_school/university_of_arizona/eht_software/hallmark/demo

In [13]:
repo1.checkout("main")

True

In [14]:
%%bash
echo "Files after checkout back to main:"
ls repo1/*.h5

Files after checkout back to main:
repo1/a0.75_i0.h5
repo1/a0.75_i120.h5
repo1/a0.75_i30.h5
repo1/a0.75_i60.h5
repo1/a0.75_i90.h5
repo1/a0_i0.h5
repo1/a0_i120.h5
repo1/a0_i30.h5
repo1/a0_i60.h5
repo1/a0_i90.h5

## 5. Filter Functionality

We can also show that we can filter data from the ParaFrame Object

In [15]:
# Single Parameter Filter
paraframe(a=0)

         path    a      i
5    a0_i0.h5  0.0    0.0
6  a0_i120.h5  0.0  120.0
7   a0_i30.h5  0.0   30.0
8   a0_i60.h5  0.0   60.0
9   a0_i90.h5  0.0   90.0

In [16]:
# Or Filter
paraframe(a=0, i=30)

           path     a      i
2  a0.75_i30.h5  0.75   30.0
5      a0_i0.h5  0.00    0.0
6    a0_i120.h5  0.00  120.0
7     a0_i30.h5  0.00   30.0
8     a0_i60.h5  0.00   60.0
9     a0_i90.h5  0.00   90.0

In [17]:
# And Filter
paraframe(a=0)(i=30)

        path    a     i
7  a0_i30.h5  0.0  30.0

In [18]:
# Masking Filter retains Pandas DataFrame functionality
paraframe[(30 <= paraframe.i) & (paraframe.i <= 100)]

           path     a     i
2  a0.75_i30.h5  0.75  30.0
3  a0.75_i60.h5  0.75  60.0
4  a0.75_i90.h5  0.75  90.0
7     a0_i30.h5  0.00  30.0
8     a0_i60.h5  0.00  60.0
9     a0_i90.h5  0.00  90.0